### ISSUE TITLE
Error: Matrix index exceeds the deletion range

### ISSUE THREAD

**Issue by Springder** [iqiukp/ZoomPlot-MATLAB#2]
When I used BaseZoom after boxplot, the error happened.
Error:
Matrix index exceeds the deletion range
error BaseZoom/creatSubAxes (line 503)
                            numChildren_(ii) = [];
error BaseZoom/insertSubAxes (line 248)
                            obj.creatSubAxes;
error BaseZoom/plot (line 193)
                    obj.insertSubAxes;
We can repeat it by codes below:

> load carsmall
boxplot(MPG,Origin)
title('Miles per Gallon by Vehicle Origin')
xlabel('Country of Origin')
ylabel('Miles per Gallon (MPG)')
zp = BaseZoom();                                                         
zp.plot;

**Comment by iqiukp** [comment]
Hi. The current version of ZoomPlot does not support boxplots.

**Comment by Springder** [comment]
That's very regrettable. 
Could we support this feature? I think ZooPlot is very useful, and not supporting boxplot is a bit imperfect.

**Comment by iqiukp** [comment]
Adding support for multiple figure types is not an easy task, but standard figures like barplot will be in the updated plan for ZoomPlot. I'm working on adding support for double Y-axis plots, as well as JSON file-based parameter customization. Thanks again for your support of ZoomPlot!
