### ISSUE TITLE
how to use it in uitab handle

### ISSUE THREAD

**Issue by liaozhaishusheng** [iqiukp/ZoomPlot-MATLAB#4]
Thank you so much for your tool. It has been extremely helpful.

I have a question recently - I frequently use uitabgroup/uitab in my figures, the fact is BaseZoom could detects the last handle (tab2_axes), but it fails display any information within the box. Is there any way showing it correctly?

**Comment by iqiukp** [comment]
Hello. If possible, please provide a sample code for using zoomplot in uitabgroup/uitab and send it to my email: iqiukp@outlook.com. I will try to reproduce the error and fix it.

**Comment by liaozhaishusheng** [comment]
> Hello. If possible, please provide a sample code for using zoomplot in uitabgroup/uitab and send it to my email: [iqiukp@outlook.com](mailto:iqiukp@outlook.com). I will try to reproduce the error and fix it.

Thanks, I just sent it to you. Please check the attachment (uitab_test.m) in the email.
